---

- name: Create a VIP, pool, pool members and nodes
  hosts: localhost
  connection: local
  vars:
     big-ip: "10.0.0.181"

  tasks:
      - name: Create a pool
        bigip_pool:
            lb_method: "ratio_member"
            name: "web"
            password: "admin"
            server: "{{big-ip}}"
            slow_ramp_time: "120"
            user: "admin"
            validate_certs: "no"
        delegate_to: localhost

      - name: Create node1
        bigip_node:
            host: "10.10.10.10"
            name: "node-1"
            password: "admin"
            server: "{{big-ip}}"
            user: "admin"
            validate_certs: "no"
        delegate_to: localhost

      - name: Create node2
        bigip_node:
            host: "10.10.10.20"
            name: "node-2"
            password: "admin"
            server: "{{big-ip}}"
            user: "admin"
            validate_certs: "no"
        delegate_to: localhost

      - name: Add nodes to pool
        bigip_pool_member:
            description: "webserver-1"
            host: "{{ item.host }}"
            name: "{{ item.name }}"
            password: "admin"
            pool: "web"
            port: "80"
            server: "{{big-ip}}"
            user: "admin"
            validate_certs: "no"
        delegate_to: localhost
        with_items:
            - host: "10.10.10.10"
              name: "node-1"
            - host: "10.10.10.20"
              name: "node-2"

      - name: Create a VIP
        bigip_virtual_server:
            description: "foo-vip"
            destination: "172.16.10.108"
            password: "admin"
            name: "vip-1"
            pool: "web"
            port: "80"
            server: "{{big-ip}}"
            snat: "Automap"
            user: "admin"
            all_profiles:
                - "http"
                - "clientssl"
            validate_certs: "no"
        delegate_to: localhost
