#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will enable the application Connector
#      service center. 
#      The steps are as follows:
#      - Verify that the target F5 device is running v13 or greater
#      - Verify that the F5 device is licensed for App Connector.
#      - Provision all desired modules including iRulesLX. This playbook will
#        provision iRulesLX if you are running Ansible 2.4 and you uncomment 
#        the provisioning module below.
#      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#      You must provision iRulesLX before running this playbook. The module
#      that performs this function will not work until Ansible 2.4 is released
#      I've left the code in and commented it out for later.
#      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
#      - This playbook will enable App Connector.
#        NOTICE: Be sure you have staged the files in the ~/ansible/playbooks
#        directory as described in the "Ansible Orchestration for Application
#        Connector deployment guide located at https://github.com/mlowcher61
#      - After running this playbook perform the manual steps described in the 
#        deployment guide prior to running the appconnector_vips playbook. 

- name: Configuring App Connecter service center
  hosts: 10.0.0.185
  connection: local
  gather_facts: no
  vars:
    appliance: "10.0.0.185"
    setup_user: "admin"
    setup_pass: "admin"
#    app_connector: "app-connector-1.0.0-44.0.noarch.rpm"
  tasks: 
#   - name: Provisioning iRulesLX
#     bigip_provision: # This module will not be supported until Ansible v2.4
#         module: "ilx"
#         level: "nominal"
#         server: "{{appliance}}"
#         user: "{{setup_user}}"
#         password: "{{setup_pass}}"
#         validate_certs: "no"
#     delegate_to: localhost
#
#   - name: Waiting 60 seconds for iRulesLX to be provisioned 
#     wait_for:
#       timeout: 60

   - name: Enabling App Connector
     raw: touch /var/config/rest/iapps/enable
