#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will provision the selected module.
#      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#      The bigip_provision module requires Ansible v2.4 or >
#      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- name: Provision modules
  hosts: 10.0.0.160
  connection: local

  tasks: 
   - name: Provisioning modules
     bigip_provision:
         module: "gtm"
         level: "nominal"
         server: "10.0.0.160"
         user: "admin"
         password: "admin"
         validate_certs: "no"
     delegate_to: localhost
