#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will provision the selected module.

- name: Provision module
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
   server1: 10.0.0.180
   server2: 10.0.0.181
   module1: asm
   module2: apm
   setup_user: admin
   setup_pass: admin

   

  tasks: 
   - name: Provisioning module
     bigip_provision:
      module: "{{ item.module }}"
      level: "nominal"
      server: "{{ item.server }}"
      user: "{{setup_user}}"
      password: "{{setup_pass}}"
      validate_certs: "no"
     delegate_to: localhost
     with_items:
        - server: "{{ server1 }}"
          module: "asm"
          module: "apm"
        - server: "{{ server2 }}"
          module: "asm"
          module: "apm"
