#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will create a child tcp monitor based on the
#      the parent monitor stated in the "type" attribute. The "state" attribute 
#      should be set to "present" to create the monitor and to "absent" to delet
#      the monitor. The "send" and "receive" attributes have been commented out
#      but are there to show how to add them if desired.

- name: Connecting...
  hosts: "10.0.0.185"
  connection: local

  tasks: 
   - name: Set the banner for the SSHD service from a file
     bigip_device_sshd:
         banner: "enabled"
         banner_text: "{{ lookup('file', '/var/tmp/SSHD-banner.txt') }}"
         password: "admin"
         server: "10.0.0.185"
         user: "admin"
     delegate_to: localhost
