#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will create an HA configuraton.
#

- name: Set up a BIG-IP HA pair
  hosts: localhost
  gather_facts: false

  vars:
   bigip1_ip: 10.0.0.180
   bigip2_ip: 10.0.0.181
   bigip1_old_name: bigip1
   bigip1_new_name: bigip1.attlab.com
   bigip2_old_name: bigip1
   bigip2_new_name: bigip2.attlab.com
   bigip1_selfip: 1.1.1.4
   bigip2_selfip: 1.1.1.5
   ha_vlan: ha_vlan
   setup_user: admin
   setup_pass: admin

  tasks:
  - name: Configure SELF-IP for HA on the BIG-IP1
    bigip_selfip:
     server: "{{ bigip1_ip }}"
     user: "{{setup_user}}"
     password: "{{setup_pass}}"
     validate_certs: False
     name: "Selfip1_HA"
     address: "{{ bigip1_selfip }}"
     netmask: "255.255.255.0"
     vlan: "{{ ha_vlan }}"
     traffic_group: "traffic-group-local-only"
    delegate_to: localhost

  - name: Configure SELF-IP for HA on the BIG-IP2
    bigip_selfip:
     server: "{{ bigip2_ip }}"
     user: "admin"
     password: "admin"
     validate_certs: False
     name: "Selfip2_HA"
     address: "{{ bigip2_selfip }}"
     netmask: "255.255.255.0"
     vlan: "{{ ha_vlan }}"
     traffic_group: "traffic-group-local-only"
    delegate_to: localhost

  - name: Change device name of BIG-IP1
    bigip_command:
      server: "{{ bigip1_ip }}"
      user: "{{setup_user}}"
      password: "{{setup_pass}}"
      commands:
      - mv cm device {{ bigip1_old_name }} {{ bigip1_new_name }}
    delegate_to: localhost

  - name: Change device name of BIG-IP2
    bigip_command:
      server: "{{ bigip2_ip }}"
      user: "{{setup_user}}"
      password: "{{setup_pass}}"
      commands:
      - mv cm device {{ bigip2_old_name }} {{ bigip2_new_name }}
    delegate_to: localhost

  - name: Set config sync address on BIG-IP1
    bigip_command:
      server: "{{ bigip1_ip }}"
      user: "{{setup_user}}"
      password: "{{setup_pass}}"
      commands:
      - modify cm device {{ bigip1_new_name }} configsync-ip {{ bigip1_selfip }}
    delegate_to: localhost

  - name: Set config sync address on BIG-IP2
    bigip_command:
      server: "{{ bigip2_ip }}"
      user: "{{setup_user}}"
      password: "{{setup_pass}}"
      commands:
      - modify cm device {{ bigip2_new_name }} configsync-ip {{ bigip2_selfip }}
    delegate_to: localhost

  - name: Set unicast address on BIG-IP1
    bigip_command:
      server: "{{ bigip1_ip }}"
      user: "{{setup_user}}"
      password: "{{setup_pass}}"
      commands:
      - modify cm device {{ bigip1_new_name }} unicast-address { { ip {{ bigip1_selfip }} } { ip {{ bigip1_ip }} } }
    delegate_to: localhost

  - name: Set unicast address on BIG-IP2
    bigip_command:
      server: "{{ bigip2_ip }}"
      user: "{{setup_user}}"
      password: "{{setup_pass}}"
      commands:
      - modify cm device {{ bigip2_new_name }} unicast-address { { ip {{ bigip2_selfip }} } { ip {{ bigip2_ip }} } }
    delegate_to: localhost

  - name: Discover device for trust on BIG-IP1
    bigip_command:
      server: "{{ bigip1_ip }}"
      user: "{{setup_user}}"
      password: "{{setup_pass}}"
      commands:
      - modify cm trust-domain Root ca-devices add { {{ bigip2_ip }} } name {{ bigip2_new_name }} username "{{setup_user}}" password "{{setup_pass}}"
    delegate_to: localhost

  - name: Check sync and failover status of BIG-IP1
    bigip_command:
      server: "{{ bigip1_ip }}"
      user: "{{setup_user}}"
      password: "{{setup_pass}}"
      commands:
       - show cm sync-status
      wait_for:
       - result[0] contains "green"
      match: all
    delegate_to: localhost

  - name: Check sync and failover status of BIG-IP2
    bigip_command:
      server: "{{ bigip2_ip }}"
      user: "{{setup_user}}"
      password: "{{setup_pass}}"
      commands:
       - show cm sync-status
      wait_for:
       - result[0] contains "green"
      match: all
    delegate_to: localhost

  - name: Create device group of type sync-failover
    bigip_command:
      server: "{{ bigip1_ip }}"
      user: "{{setup_user}}"
      password: "{{setup_pass}}"
      commands:
       - create cm device-group DG devices add { {{ bigip1_new_name }} {{ bigip2_new_name }} } type sync-failover network-failover enabled
    delegate_to: localhost

  - name: Perform initial sync of device-group
    bigip_command:
      server: "{{ bigip1_ip }}"
      user: "{{setup_user}}"
      password: "{{setup_pass}}"
      commands:
       - run cm config-sync to-group DG
    delegate_to: localhost

  - name: Confirm HA pair is formed
    bigip_command:
      server: "{{ bigip1_ip }}"
      user: "{{setup_user}}"
      password: "{{setup_pass}}"
      commands:
       - show cm sync-status
      wait_for:
       - result[0] contains "high-availability"
    delegate_to: localhost
